### ISSUE TITLE
Non-keyboard interface

### ISSUE THREAD

**Issue by edemaine** [edemaine/timer#1]
We need a reasonable non-keyboard interface for mobile, tablets, etc.  Some ideas:

* Tap on top half of a number to increment
* Tap on bottom half of a number to decrement
* Tap on colon to start/stop, long tap to reset?
* Or use bottom line for pause/reset buttons?

**Comment by edemaine** [comment]
As a partial solution, the keyboard shortcuts (help) are now clickable.

**Comment by ubdussamad** [comment]
Something like a dial or a ring around the time could be useful, one will have to rotate a notch on the ring clockwise to increase time and vice versa. but that’ll be a pain to implement.
